title: "Hitterøy Kystlag"
email: "post@hitteroykystlag.no"
description: >
  Hitterøy Kystlag bevarer og formidler kystkultur gjennom båtbygging, fiske og restaurering av gamle dieselmotorer.

url: "https://hitteroykystlag.no"
baseurl: ""

#theme: jekyll-theme-minimal
#theme: jekyll-theme-primer
#theme: jekyll-theme-midnight
remote_theme: "zerostaticthemes/jekyll-atlantic-theme"
logo: "/assets/img/logo.png"
favicon: "/assets/img/logo.png"
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme 
  