title: "Hitterøy Kystlag"
email: "post@hitteroykystlag.no"
description: >
  Hitterøy Kystlag bevarer og formidler kystkultur gjennom båtbygging, fiske og restaurering av gamle dieselmotorer.
baseurl: ""
url: "https://hitteroykystlag.github.io"
remote_theme: "zerostaticthemes/jekyll-atlantic-theme"
logo: "/assets/img/logo.png"
favicon: "/assets/img/logo.png"
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
