title: "Hitterøy Kystlag"
email: "post@hitteroykystlag.no"
description: >
  Hitterøy Kystlag bevarer og formidler kystkultur gjennom båtbygging, fiske og restaurering av gamle dieselmotorer.

url: "https://hitteroykystlag.no"
baseurl: "/hitteroykystlag.github.io"

#theme: jekyll-theme-midnight
#remote_theme: "zerostaticthemes/jekyll-atlantic-theme"
remote_theme: pages-themes/architect@v0.2.0
favicon: "/assets/img/logo.png"
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme 
  